import { Theme } from '@rainbow-me/rainbowkit';
export const rainbowKitTheme: Theme = {
  darkMode: {
    blurs: {
      modalOverlay: '...',
    },
    colors: {
      accentColor: '#3383C5',
      accentColorForeground: '#ffffff',
      actionButtonBorder: 'transparent',
      actionButtonBorderMobile: 'transparent',
      actionButtonSecondaryBackground: '#c5c6c6',
      closeButton: '#ffffff',
      closeButtonBackground: 'transparent',
      connectButtonBackground: '#3383C5',
      connectButtonBackgroundError: '#BC0030',
      connectButtonInnerBackground: '#3383C5',
      connectButtonText: '#ffffff',
      connectButtonTextError: '#ffffff',
      connectionIndicator: '#192648',
      downloadBottomCardBackground: '#747c90',
      downloadTopCardBackground: '#839bbd',
      error: '#525c76',
      generalBorder: 'transparent',
      generalBorderDim: 'transparent',
      menuItemBackground: '#1d3557',
      modalBackdrop: 'rgba(0, 0, 0, 0.5)',
      modalBackground: 'rgba(7, 22, 47, 1)',
      modalBorder: 'transparent',
      modalText: '#ffffff',
      modalTextDim: 'rgba(255, 255, 255, 0.6)',
      modalTextSecondary: 'rgba(255, 255, 255, 0.6)',
      profileAction: '#1d3557',
      profileActionHover: '#1d3557',
      profileForeground: 'rgba(7, 22, 47, 1)',
      selectedOptionBorder: 'transparent',
      standby: '#f9f8ff',
    },
    fonts: {
      body: 'Inter',
    },
    radii: {
      actionButton: '20px',
      connectButton: '10px',
      menuButton: '3px',
      modal: '8px',
      modalMobile: '13.5px',
    },
    shadows: {
      connectButton: '0px 4px 4px rgba(0, 0, 0, 0.25)',
      dialog:
        '4px 4px 10px rgba(0,0,0,0.24), 2px 2px 4px rgba(0, 0, 0, 0.12),1px 2px 2px rgba(0, 0, 0, 0.12)',
      profileDetailsAction: '...',
      selectedOption: '...',
      selectedWallet: '...',
      walletLogo: '...',
    },
  },
  lightMode: {
    blurs: {
      modalOverlay: 'rgba(255, 255, 255, 0.8)',
    },
    colors: {
      accentColor: '#72b3e8',
      accentColorForeground: '#000000',
      actionButtonBorder: 'transparent',
      actionButtonBorderMobile: 'transparent',
      actionButtonSecondaryBackground: '#3d3d3d',
      closeButton: '#000000',
      closeButtonBackground: 'transparent',
      connectButtonBackground: '#72b3e8',
      connectButtonBackgroundError: '#d75373',
      connectButtonInnerBackground: '#72b3e8',
      connectButtonText: '#000000',
      connectButtonTextError: '#000000',
      connectionIndicator: '#d6e0f0',
      downloadBottomCardBackground: '#bcbcd4',
      downloadTopCardBackground: '#c6d0e3',
      error: '#adaebc',
      generalBorder: '#e0e0e0',
      generalBorderDim: '#e0e0e0',
      menuItemBackground: '#e1e7f0',
      modalBackdrop: 'rgba(255, 255, 255, 0.5)',
      modalBackground: 'rgba(248, 248, 248, 1)',
      modalBorder: 'transparent',
      modalText: '#000000',
      modalTextDim: 'rgba(0, 0, 0, 0.6)',
      modalTextSecondary: 'rgba(0, 0, 0, 0.6)',
      profileAction: '#e1e7f0',
      profileActionHover: '#e1e7f0',
      profileForeground: 'rgba(248, 248, 248, 1)',
      selectedOptionBorder: '#e0e0e0',
      standby: '#060613',
    },
    fonts: {
      body: 'Inter',
    },
    radii: {
      actionButton: '20px',
      connectButton: '10px',
      menuButton: '3px',
      modal: '8px',
      modalMobile: '13.5px',
    },
    shadows: {
      connectButton: '0px 2px 2px rgba(0, 0, 0, 0.1)',
      dialog:
        '2px 2px 5px rgba(0, 0, 0, 0.1), 1px 1px 2px rgba(0, 0, 0, 0.06), 0.5px 1px 1px rgba(0, 0, 0, 0.06)',
      profileDetailsAction: '0px 2px 2px rgba(0, 0, 0, 0.1)',
      selectedOption: '0px 2px 2px rgba(0, 0, 0, 0.1)',
      selectedWallet: '0px 2px 2px rgba(0, 0, 0, 0.1)',
      walletLogo: '0px 2px 2px rgba(0, 0, 0, 0.1)',
    },
  },
};
